// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvcqkkygnfvduszlkutw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y3Fra3lnbmZ2ZHVzemxrdXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTY3MTksImV4cCI6MjA2NTU3MjcxOX0.yjjl7V0Ww78QJOpoip1DZ726yy5mSmlWKX3OPbpUK_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);